### ISSUE TITLE
Bug in AWS EB CLI

### ISSUE THREAD

**Issue by sannies** [nhumrich/nhumrich.github.io#1]
Hi Nick, 
after an hour of research I [know that you're married, seen a few facebook photos of you and your wife](https://scontent-fra.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/488261_3960458004808_1722351198_n.jpg?oh=7ed781332122987fb2a4938b16138744&oe=55E19AA1), you seem to become a [parent soon](http://registry.thebump.com/nick-humrich-rebecca-humrich-january-2015-wa/8322913) but I cannot get in touch with you except this weird workaround of creating a bug in your blog. 

Please have a look at operations/create.py in your AWS EB CLI project.  It states: 

```
        if not elbpublic:
            publicip = io.get_boolean_response(
                text=prompts['vpc.elbpublic'])
```

but of course it should be 

```
        if not elbpublic:
            elbpublic = io.get_boolean_response(
                text=prompts['vpc.elbpublic'])
```

classic copy'n'paste I'd say.

Best Regards,
Sebastian

**Comment by nhumrich** [comment]
Hey man. Thanks for this. Is this blocking you right now?

Nick

**Comment by sannies** [comment]
Nope, not blocking as I can set it on the command line via --vpc.elbpublic. I just wasted two hours and wanted to save the next one from wasting 2 hours as well.
